"""add plaid_items, accounts, transactions tables

Revision ID: 351e1dac0bc1
Revises: 4d8c29b768f8
Create Date: 2026-03-18 14:42:05.504537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351e1dac0bc1'
down_revision: Union[str, None] = '4d8c29b768f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('cursor', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plaid_item_id', sa.UUID(), nullable=True),
    sa.Column('plaid_account_id', sa.String(length=255), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mask', sa.String(length=4), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_plaid_account_id', 'accounts', ['plaid_account_id'], unique=True, postgresql_where='plaid_account_id IS NOT NULL')
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('plaid_txn_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', sa.literal_column('date DESC')], unique=False)
    op.create_index('ix_transactions_plaid_txn_id', 'transactions', ['plaid_txn_id'], unique=True, postgresql_where='plaid_txn_id IS NOT NULL')
    op.create_index('ix_transactions_user_category_date', 'transactions', ['user_id', 'category_id', 'date'], unique=False)
    op.create_index('ix_transactions_user_date', 'transactions', ['user_id', sa.literal_column('date DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_date', table_name='transactions')
    op.drop_index('ix_transactions_user_category_date', table_name='transactions')
    op.drop_index('ix_transactions_plaid_txn_id', table_name='transactions', postgresql_where='plaid_txn_id IS NOT NULL')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_accounts_plaid_account_id', table_name='accounts', postgresql_where='plaid_account_id IS NOT NULL')
    op.drop_table('accounts')
    op.drop_table('plaid_items')
    # ### end Alembic commands ###
