"""add rotated_at, pending_mfa_secret, cascade FKs

Revision ID: 4d8c29b768f8
Revises: 6910aeaaf6d9
Create Date: 2026-03-18 13:52:44.723010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8c29b768f8'
down_revision: Union[str, None] = '6910aeaaf6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_user_id_fkey'), 'categories', type_='foreignkey')
    op.drop_constraint(op.f('categories_parent_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('oauth_accounts_user_id_fkey'), 'oauth_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'oauth_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('refresh_tokens', sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_settings_user_id_fkey'), 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('pending_mfa_secret', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_mfa_secret')
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(op.f('user_settings_user_id_fkey'), 'user_settings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_column('refresh_tokens', 'rotated_at')
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('oauth_accounts_user_id_fkey'), 'oauth_accounts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_parent_id_fkey'), 'categories', 'categories', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('categories_user_id_fkey'), 'categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
