"""add plaid sandbox fields

Revision ID: cd3a428d235e
Revises: b3c4d5e6f7a8
Create Date: 2026-03-23 12:32:15.952731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3a428d235e'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_items', sa.Column('environment', sa.String(length=20), server_default='production', nullable=False))
    op.add_column('users', sa.Column('use_plaid_sandbox', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_plaid_sandbox')
    op.drop_column('plaid_items', 'environment')
    # ### end Alembic commands ###
